In [48]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 
from sklearn import preprocessing 
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [49]:
train = pd.read_csv('./data/Train_UWu5bXk.csv')
test = pd.read_csv('./data/Test_u94Q5KV.csv')
LF_notation = train.index[train['Item_Fat_Content'] == 'LF'].tolist()
len(LF_notation)

316

In [55]:
## preprocessing 
### mean imputations 
train['Item_Weight'].fillna((train['Item_Weight'].mean()), inplace=True)
test['Item_Weight'].fillna((test['Item_Weight'].mean()), inplace=True)

 ### reducing fat content to only two categories 
train['Item_Fat_Content'] = train['Item_Fat_Content'].replace(['Low Fat','LF'], ['Low Fat','Low Fat']) 
train['Item_Fat_Content'] = train['Item_Fat_Content'].replace(['reg'], ['Regular']) 
#print(train.head(50))
#print(train.index[train['Item_Fat_Content'] == 'LF'].tolist())
test['Item_Fat_Content'] = test['Item_Fat_Content'].replace(['low fat','LF'], ['Low Fat','Low Fat']) 
test['Item_Fat_Content'] = test['Item_Fat_Content'].replace(['reg'], ['Regular']) 
train['Outlet_Establishment_Year'] = 2013 - train['Outlet_Establishment_Year'] 
test['Outlet_Establishment_Year'] = 2013 - test['Outlet_Establishment_Year'] 

train['Outlet_Size'].fillna('Small',inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [60]:
test['Outlet_Size'].fillna('Small',inplace=True)

train['Item_Visibility'] = np.sqrt(train['Item_Visibility'])
test['Item_Visibility'] = np.sqrt(test['Item_Visibility'])
trian = train.fillna(0)
test = test.fillna(0)

col = ['Outlet_Size','Outlet_Location_Type','Outlet_Type','Item_Fat_Content']
test['Item_Outlet_Sales'] = 0
combi = train.append(test)
number = preprocessing.LabelEncoder()
for i in col:
 combi[i] = number.fit_transform(combi[i].astype('str'))
 combi[i] = combi[i].astype('object')
train = combi[:train.shape[0]]
test = combi[train.shape[0]:]
test.drop('Item_Outlet_Sales',axis=1,inplace=True)

## removing id variables 
tpot_train = train.drop(['Outlet_Identifier','Item_Type','Item_Identifier'],axis=1)
tpot_test = test.drop(['Outlet_Identifier','Item_Type','Item_Identifier'],axis=1)
target = tpot_train['Item_Outlet_Sales']
tpot_train.drop('Item_Outlet_Sales',axis=1,inplace=True)

# finally building model using tpot library
from tpot import TPOTRegressor
X_train, X_test, y_train, y_test = train_test_split(tpot_train, target,
 train_size=0.75, test_size=0.25)
X_train

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
5303,8.760000,0,0.954274,126.7336,1987,0,2,1
8105,20.500000,1,0.000000,83.2592,2007,2,1,1
4950,20.500000,1,0.966512,194.1478,2007,2,1,1
4286,16.000000,1,0.964551,88.5856,1997,2,0,1
3133,17.000000,1,0.944886,141.2470,2004,2,1,1
487,12.857645,0,0.968765,74.0354,1985,2,0,0
2925,8.420000,0,0.959483,217.4192,2009,1,2,2
5642,12.857645,1,0.971672,145.5102,1985,1,2,3
3560,15.700000,0,0.952798,181.3660,2002,2,1,1
2848,11.500000,0,0.941430,131.3942,1999,1,0,1
2985,19.350000,1,0.961747,48.5034,1999,1,0,1
4984,10.195000,0,0.968197,112.1886,1997,2,0,1
2948,12.857645,0,0.945227,99.7042,1985,1,2,3
5856,12.650000,0,0.953411,114.1202,1987,0,2,1
3233,6.325000,0,0.968050,99.2042,2004,2,1,1
5353,16.350000,0,0.966632,198.2426,1998,2,2,0
5725,19.350000,0,0.945512,65.6168,1997,2,0,1
385,15.250000,0,0.944909,86.2198,2004,2,1,1
6566,13.000000,1,0.946716,58.0220,1987,0,2,1
2128,5.655000,0,0.962261,165.8500,2004,2,1,1
423,20.350000,1,0.000000,256.7672,2009,1,2,2
4520,20.500000,0,0.949442,120.0756,1997,2,0,1
4579,13.100000,0,0.960474,168.4158,1999,1,0,1
6943,11.500000,1,0.950048,107.5254,2002,2,1,1
7229,12.857645,1,0.951415,91.6804,1985,1,2,3
5806,12.857645,0,0.935427,36.7190,1985,1,2,3
1866,11.500000,0,0.959929,189.2530,1999,1,0,1
7767,16.500000,1,0.961274,102.1332,1999,1,0,1
1275,21.000000,0,0.954146,193.8478,2007,2,1,1
4810,19.350000,0,0.938010,120.9098,2002,2,1,1
...,...,...,...,...,...,...,...,...
4626,17.000000,1,0.944919,144.2470,2002,2,1,1
6969,19.500000,0,0.935749,57.1614,1987,0,2,1
4610,11.650000,0,0.951169,187.3240,2002,2,1,1
5766,12.857645,0,0.966405,123.3414,1985,2,0,0
2280,20.850000,1,0.957534,88.1514,2004,2,1,1
2351,16.100000,1,0.953684,126.5362,2007,2,1,1
1097,12.857645,1,0.951009,181.1660,1985,1,2,3
1596,7.325000,0,0.963692,90.3146,2009,1,2,2
4581,12.300000,0,0.929771,73.8380,2007,2,1,1
2546,20.100000,0,0.960321,108.9228,2009,1,2,2
54,12.150000,0,0.946060,151.4708,2007,2,1,1
443,12.350000,0,0.972165,120.5124,1999,1,0,1
1495,11.000000,1,0.968983,221.5798,2004,2,1,1
7417,8.775000,0,0.941869,109.5228,2002,2,1,1
525,16.350000,1,0.957582,225.9062,1997,2,0,1
5224,13.150000,0,0.959981,181.6950,1998,2,2,0
296,7.090000,0,0.925836,47.9034,2004,2,1,1
7266,9.500000,0,0.962292,188.4872,2009,1,2,2
6770,5.940000,1,0.946371,186.7556,1997,2,0,1
1092,12.857645,0,0.964575,187.8898,1985,1,2,3
7521,15.750000,0,0.955661,195.3452,1987,0,2,1
4947,15.700000,0,0.971822,59.2562,1987,0,2,1
5362,17.750000,0,0.960556,111.4544,2002,2,1,1
5988,17.000000,0,0.955894,220.0114,2007,2,1,1
2452,10.100000,0,0.945159,76.4670,2004,2,1,1
1537,4.880000,1,0.000000,53.1298,2004,2,1,1
2340,15.700000,0,0.000000,43.3770,1998,2,2,0
1533,20.200000,0,0.960213,91.4462,2002,2,1,1
2363,11.650000,0,0.951223,185.9240,2007,2,1,1
1164,7.855000,1,0.960115,218.4482,2004,2,1,1

In [61]:
tpot = TPOTRegressor(generations=5, population_size=50, verbosity=2)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('tpot_boston_pipeline.py')

Warning: xgboost.XGBRegressor is not available and will not be used by TPOT.

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''